### ISSUE TITLE
Pass middleware to ReduxCache managed store

### ISSUE THREAD

**Issue by rportugal** [rportugal/apollo-cache-redux#12]
If the `store` option is not passed to the `ReduxCache` constructor, it will create and manage a Redux store automatically. However, it doesn't allow middleware to be set up. `ReduxCache` constructor needs a `middleware` option.

**Comment by quadsurf** [comment]
Awesome library!

Is the lack of a middleware option going to impede web-socket subscription middleware? Or is this lack of middleware option more so relating to libs like redux-thunk, redux-promise, redux-saga, and/or redux-observable???

Are there plans to add support for this middleware option?

**Comment by rportugal** [comment]
Thanks for your question, @quadsurf !

The issue only applies if you don't pass an existing store to the `ReduxCache` constructor. If you use it in the same way as the README (have an existing store, which you want to add Apollo to) you should be fine to use all the libraries you mentioned. It uses a very similar interface to Apollo Client 1.x, and those libraries were known to work fine with it.

**Comment by rportugal** [comment]
Removed self-managed store in #18 and will only take an existing store.
