### ISSUE TITLE
Pass ReduxNormalizedCache constructor config.store

### ISSUE THREAD

**Issue by grwgreg** [rportugal/apollo-cache-redux#13]
https://github.com/rportugal/apollo-cache-redux/blob/0.1.0-alpha.7/src/reduxCache.ts#L22 is always passing an empty object as the first parameter. I think it should be passing config.store. Currently it always overwrites my initial state with an empty object and messes with my server side rendering.

**Comment by rportugal** [comment]
Hi @grwgreg , thanks for reporting this issue.
I can add a `data` option to the `ReduxCache` constructor, but I think that from `InMemoryCache`'s interface (which I'm trying to emulate), any initial state should be restored using the `restore()` method. 
I don't have any SSR projects I can try it on, can you provide an example?
Thanks!
