### ISSUE TITLE
Anyway to hide passwords

### ISSUE THREAD

**Issue by oseibonsu** [rportugal/apollo-cache-redux#15]
If I am using a mutation to authenticate users is there any way to hide the password being sent?

**Comment by rportugal** [comment]
I wouldn't expect this being dependent on the cache implementation. 
From https://www.apollographql.com/docs/react/basics/mutations.html#store-updates , you're able to filter out any sensitive data before storing it on the cache.

If you're concerned about having data as part of the mutation/variables you submit to your GraphQL server, it should be fine, as long as you use HTTPS.
