### ISSUE TITLE
redux-immutable Support?

### ISSUE THREAD

**Issue by elandesign** [rportugal/apollo-cache-redux#19]
I'm currently trying to upgrade our Apollo 1.x app, which has a bunch of non-apollo redux requirements to Apollo 2.x so this project filled me with hope, but I'm having some issues which I *think* may be because we use `redux-immutable`.

It seems that every `graphql(MY_QUERY)(MyComponent)` HOC we create never actually receives the query result in `props.data`.

My problem may well be elsewhere, but do you know if our use of `redux-immutable` along with your module is likely/known to cause problems?

Thanks,
Paul.

**Comment by rportugal** [comment]
Hi Paul, thanks for your question.
I'm not aware of any incompatibilities with `redux-immutable` or any other library at the moment, but I wouldn't be surprised. 
Can you provide a small example, so I can take a look? Did it work with no issues with Apollo 1.x? Did it output any errors? 
Thanks.

**Comment by elandesign** [comment]
I've tried putting together a small example app to reproduce the issue in isolation, but typically that seems to work as expected - it may be something else in our stack that's causing problems.

I'll close this issue for now and keep chipping away at it - if anyone else is having the same problems feel free to message me.
