### ISSUE TITLE
Dispatch Clear apollo store

### ISSUE THREAD

**Issue by Biromain** [rportugal/apollo-cache-redux#24]
How to dispatch apollo store clear? Like on user logout.
I can create my own action to clear it but it's probably not the better way.

Regards,

**Comment by rportugal** [comment]
Hi @Biromain , the store should be cleared via the standard Apollo Cache methods, not through a Redux action directly. I believe it's `client.cache.reset()`, or something similar.

**Comment by Biromain** [comment]
Hi,
Oh, where is my brain, Apollo client clear only Apollo cache. 
Thank you for anwser and for your module.

Regards,
