### ISSUE TITLE
How does it vary from using plain Redux?

### ISSUE THREAD

**Issue by rwieruch** [rportugal/apollo-cache-redux#25]
Hello @rportugal Thanks for your efforts with this package! I have a couple of questions and I am really looking forward to get some answers here.

Basically my question is: Apart from having a different cache implementation for Apollo Client itself, how does the (Redux) usage vary **in contrast** to using Redux next to Apollo Client **without** this package?

First I implemented a [minimal project](https://github.com/rwieruch/react-apollo-link-state-redux-example) by using Apollo Client and Redux **side by side**.  The setup can be found in the *src/index.js* and the usage in the *src/App.js*. Next I [refactored it](https://github.com/rwieruch/react-apollo-link-state-apollo-cache-redux-example) to using this package. Only the setup changes in the *src/index.js* fole and the state layer is one more level deeply nested because of `combineReducer` in the `mapStateToProps` function (in *src/App.js*), but apart from this nothing changes. 

1) Maybe I don't really understand the intention of the package, because I have never used Apollo Client 1.x where Redux was the default cache implementation. So I would love if someone could help me out here :) Perhaps the usage in the *src/App.js* is correct as it is, but something else changes that I am not aware of when using Redux as underlying cache.

2) The other thing which isn't clear to me is whether there would be something different in the **usage** of Redux in the *src/App.js* file when using this package (apart from having access to the Apollo Client instance in `mapStateToProps` and `mapDispatchToProps`).

3) Even though the Redux store instance is used in the Apollo Cache instance (and I guess should be implicitly) accessible due to React's Context API, you still need to use the Provider component from `react-redux` next to the ApolloProvider.

Thank you for your time! At the moment I am trying to grasp how to connect Redux and Apollo Client, because lots of people are confused about it. So I try to getter a better understanding about it. Maybe it helps that I ended up trying this package because of this issue https://github.com/apollographql/apollo-client/issues/2593

**Comment by rportugal** [comment]
Hey @rwieruch , thanks for the question.

It's mostly about getting for free the functionality revolving Redux and associated packages, like redux-persist.

The way I see it is there's two types of state: API data and actual app state.
I think it’s easier to understand with an example. Let’s pretend you’re building a UI for a Netflix-like application, in which you use GraphQL to fetch movie details etc. You could have Redux to store e.g. navigation and auth state (current menu, currently selected item, auth tokens, etc) and then Apollo Client (with or without this cache) to store API data. With this cache you could for example, persist all that state (GraphQL + app state), and when you restart the app, you could rehydrate the store and everything will be as it was before, all using packages from the Redux ecosystem .
However, you wouldn't use regular `react-redux` helpers like `mapStateToProps` with this package (for the `apollo` reducer). You should always use Apollo Client `graphql` hoc or `Query`, as that’s actually what manages this and all other caches. In summary, for the imaginary Netflix-like app, you could have these 3 reducers: `auth`, `navigation`, `apollo`, but would only use `mapStateToProps` with the first two.

Hope that answers your questions, let me know if it doesn't :)

**Comment by rwieruch** [comment]
Thanks for your response @rportugal 

So as I understand you, the main focus of the package is having all the tools from the Redux ecosystem for free without using react-redux necessarily. But as you mentioned in your example, you could opt-in `react-redux` for the local state (auth, navigation) while using the `graphql` HOC or the Query component for the remote data.
