### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by tim-soft** [rportugal/apollo-cache-redux#6]
I'm pretty keen on trying a good Redux backed Apollo cache before upgrading to the new 2.0 client, so I'm very interested in how this project is going! 

Are there any todos or glaring issues with this cache implementation? I'm heeding the warning in the readme although I plan on trying it out with a larger app soon to see how it performs. 

I'd be happy to pitch in if there is a plan in place. Extending Apollo's cache makes a lot of sense since their strategy(I think?) is to allow many cache implementations to propagate. Thanks for making the first steps!

**Comment by rportugal** [comment]
Hi @tim-soft , thanks for your comment.

I'm currently taking the `apollo-client` and `react-apollo` end-to-end tests, and replacing `InMemoryCache` with this implementation, as per @jbaxleyiii 's (of the Apollo team) suggestion. Once that's passing (almost there), and if more people try it out, that will give me a bit more confidence to remove the big warning in the readme 😄 

In regards to other features, I don't have anything in mind, except maybe some reducer naming customisation.

**Comment by tim-soft** [comment]
I will certainly take this redux cache for a test drive with one of our larger apps, lots of subscriptions/queries going on, and report back with any issues! It seems this code is nearly on par with `InMemoryCache` if it is passing most of the tests

**Comment by arif-hanif** [comment]
@rportugal i will also be trying it out next week will post findings

**Comment by rportugal** [comment]
Good news, I've been replacing `InMemoryCache` with `ReduxCache` on end-to-end tests, and after a few fixes all `react-apollo` tests are passing (177 tests), and all but one on `apollo-client` (299 out of 300).

**Comment by rportugal** [comment]
Please note the README has been updated, and the arguments to `ReduxCache` have changed slightly.
Until there's a more standard way to test caches, the tests can be found in:
https://github.com/rportugal/apollo-client/tree/cache_tester
and https://github.com/rportugal/react-apollo/tree/redux_cache_tests

**Comment by tim-soft** [comment]
That's great news! 

Looking through most of my apps, I realized that I often keep an Apollo client instance inside redux along with the cache. Needing to create the store before the client exists doesn't fit into my current way of doing things. Have any advice for this scenario?

**Comment by rportugal** [comment]
With this implementation you can either pass in an existing one as a `store` option, or if you don't pass any, it will create and manage its own store. If it's created by ReduxCache, there is currently no way of accessing the store directly, and thus, no easy way to use Redux middleware. One for the roadmap maybe? 😄 
Not sure if that fits into the way your app works.

**Comment by tim-soft** [comment]
Redux middleware would be an amazing feature! In development, it's super useful to console log graphql ops. This is the main selling point for me using redux for the cache

**Comment by rportugal** [comment]
Just rebased against the `apollo-client` master, and all tests are passing now.
Will close this issue and create a new one to track the Redux middleware work (when `ReduxCache` manages its own store). Middleware can be used if the store is created outside of the cache.
